<a href="https://colab.research.google.com/github/ankitkparashar/python/blob/main/CSML/Module4/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

**1. Basic Autograd Example 1**

In [2]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

y = w * x + b

y.backward()

print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


**2. Basic Autograd Example 2**

In [3]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

linear = nn.Linear(3, 2)
print('w: ', linear.weight)
print('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.3639,  0.4381, -0.2534],
        [-0.2374,  0.0127,  0.2803]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.2446, -0.1894], requires_grad=True)


In [4]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

pred = linear(x)

loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.0874356031417847


In [5]:
loss.backward()

print('dL/dw: ', linear.weight.grad)
print('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-0.5852,  1.1903,  0.1302],
        [-0.1435,  0.0682,  0.5556]])
dL/db:  tensor([-0.2143, -0.1508])


In [6]:
optimizer.step()

pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.0659489631652832


**3. Loading data from Numpy**

In [7]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(type(x))
y = torch.from_numpy(x)
print(y)
print(type(y))
z = y.numpy()
print(z)
print(type(z))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


**4. Input Pipeline**

In [8]:
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True,
                                             transform=transforms.ToTensor(),
                                             download=True)

image, label = train_dataset[0]
print(image.size())
print(label)

train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64,
                                           shuffle=True)

100%|██████████| 170M/170M [00:03<00:00, 55.0MB/s]


torch.Size([3, 32, 32])
6
