<a href="https://colab.research.google.com/github/ankitkparashar/python/blob/main/CSML/Module1/Week1/Jiao_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello World!')

hello_world_string = "Hello World!"
print(hello_world_string)

Hello World!
Hello World!


In [2]:
print("Variable Assignment")

a0_var = 3
A0_var = 4

print("Variable a0_var assigned value:", a0_var)
print("Variable A0_var assigned value:", A0_var)

Variable Assignment
Variable a0_var assigned value: 3
Variable A0_var assigned value: 4


In [3]:
x = 2
print("The type of x is:", type(x))

y = 2.5
print("The type of y is:", type(y))

z = "Hello World!"
print("The type of z is:", type(z))

The type of x is: <class 'int'>
The type of y is: <class 'float'>
The type of z is: <class 'str'>


In [4]:
#Addition, subtraction, multiplication, exponentiation

print("x + 3 is", x + 3)
print("x - 15 is", x - 15)
print("x * 3 is", x * 3)
print("x / 2 is", x / 2)
print("x // 2 (floor division) is", x // 2)
print("x mod 2 (remainder) is", x % 2)
print("x ** 3 (exponentiation) is", x ** 3)

x += 1
print("x += 1 is", x)
x *= 2
print("x *= 2 is", x)

x + 3 is 5
x - 15 is -13
x * 3 is 6
x / 2 is 1.0
x // 2 (floor division) is 1
x mod 2 (remainder) is 0
x ** 3 (exponentiation) is 8
x += 1 is 3
x *= 2 is 6


In [5]:
c = x + y
print("c has the value:", c, "and the type:", type(c))

d = x * y
print("d has the value:", d, "and the type:", type(d))

c has the value: 8.5 and the type: <class 'float'>
d has the value: 15.0 and the type: <class 'float'>


In [6]:
print("Booleans")

t = True
f = False

print("The type of t is:", type(t))
print("The type of f is:", type(f))

Booleans
The type of t is: <class 'bool'>
The type of f is: <class 'bool'>


In [7]:
print(t and f)
print(t or f)
print(not t)
print(t != f)
print(f == f)

False
True
False
True
True


In [8]:
import numpy as np

In [9]:
x = np.arange(0, 11, 1)
print("Integer spaced:", x)

x_new = np.linspace(0, 10, 21)
print("Linearly/Float spaced:", x_new)

#Array of ones
ones = np.ones(10)
print("Array of ones:", ones)

#Matrices
mat_a = np.array([[1, 2], [3, 4]])
print("Matrix:", mat_a)

#Identity Matrix
print(np.eye(3))

Integer spaced: [ 0  1  2  3  4  5  6  7  8  9 10]
Linearly/Float spaced: [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
Array of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Matrix: [[1 2]
 [3 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
import pandas as pd

In [11]:
#Download titanic set
titanic_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

print(titanic_df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [12]:
x_array = np.arange(0, 11, 1)
print("Length of x_array is: {}".format(len(x_array)))

Length of x_array is: 11


In [13]:
x_array[3]

np.int64(3)

In [14]:
x_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
print(x_array[3:7])

[3 4 5 6]


In [16]:
#w = A * (np.exp(-t / tau) - 1 + (t / tau))

### 10 Minutes to Pandas

In [17]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [18]:
dates = pd.date_range('20130101', periods=6)
print(dates)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [19]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)

                   A         B         C         D
2013-01-01  0.324547 -0.459218 -0.300918 -0.226213
2013-01-02 -0.368053 -1.739014  1.516996 -1.274890
2013-01-03 -0.777946 -1.443906 -2.569005  0.324704
2013-01-04  1.281193  0.672607  0.346820 -0.040114
2013-01-05 -0.182106  1.181648 -0.662382  0.487758
2013-01-06  0.416099 -0.304402  0.609796 -0.153246


In [20]:
df2 = pd.DataFrame({'A': 1.0,
                    "B": pd.Timestamp('20130102'),
                    "C": pd.Series(1, index=list(range(4)), dtype='float32'),
                    "D": np.array([3] * 4, dtype='int32'),
                    "E": pd.Categorical(["test", "train", "test", "train"]),
                    "F": 'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [21]:
df2.dtypes

,0
A,float64
B,datetime64[s]
C,float32
D,int32
E,category
F,object


In [22]:
df.head()

,A,B,C,D
2013-01-01,0.324547,-0.459218,-0.300918,-0.226213
2013-01-02,-0.368053,-1.739014,1.516996,-1.274890
2013-01-03,-0.777946,-1.443906,-2.569005,0.324704
2013-01-04,1.281193,0.672607,0.346820,-0.040114
2013-01-05,-0.182106,1.181648,-0.662382,0.487758


In [23]:
df.tail(3)

,A,B,C,D
2013-01-04,1.281193,0.672607,0.346820,-0.040114
2013-01-05,-0.182106,1.181648,-0.662382,0.487758
2013-01-06,0.416099,-0.304402,0.609796,-0.153246


In [24]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [25]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [26]:
df.to_numpy()

array([[ 0.32454657, -0.45921802, -0.30091819, -0.22621348],
       [-0.36805267, -1.73901435,  1.51699596, -1.27489027],
       [-0.77794593, -1.44390611, -2.5690052 ,  0.32470438],
       [ 1.28119257,  0.67260694,  0.34682041, -0.0401137 ],
       [-0.18210623,  1.18164825, -0.66238246,  0.48775755],
       [ 0.41609851, -0.30440229,  0.60979575, -0.1532456 ]])

In [27]:
df2.dtypes

,0
A,float64
B,datetime64[s]
C,float32
D,int32
E,category
F,object


In [28]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [29]:
df.describe()

,A,B,C,D
count,6.000000,6.000000,6.000000,6.000000
mean,0.115622,-0.348714,-0.176449,-0.147000
std,0.722985,1.142949,1.395399,0.618918
min,-0.777946,-1.739014,-2.569005,-1.274890
25%,-0.321566,-1.197734,-0.572016,-0.207972
50%,0.071220,-0.381810,0.022951,-0.096680
75%,0.393211,0.428355,0.544052,0.233500
max,1.281193,1.181648,1.516996,0.487758


In [30]:
df.T

,2013-01-01,2013-01-02,2013-01-03,2013-01-04,2013-01-05,2013-01-06
A,0.324547,-0.368053,-0.777946,1.281193,-0.182106,0.416099
B,-0.459218,-1.739014,-1.443906,0.672607,1.181648,-0.304402
C,-0.300918,1.516996,-2.569005,0.346820,-0.662382,0.609796
D,-0.226213,-1.274890,0.324704,-0.040114,0.487758,-0.153246


In [31]:
df.sort_index(axis=1, ascending=False)

,D,C,B,A
2013-01-01,-0.226213,-0.300918,-0.459218,0.324547
2013-01-02,-1.274890,1.516996,-1.739014,-0.368053
2013-01-03,0.324704,-2.569005,-1.443906,-0.777946
2013-01-04,-0.040114,0.346820,0.672607,1.281193
2013-01-05,0.487758,-0.662382,1.181648,-0.182106
2013-01-06,-0.153246,0.609796,-0.304402,0.416099


In [32]:
df.sort_values(by='B')

,A,B,C,D
2013-01-02,-0.368053,-1.739014,1.516996,-1.274890
2013-01-03,-0.777946,-1.443906,-2.569005,0.324704
2013-01-01,0.324547,-0.459218,-0.300918,-0.226213
2013-01-06,0.416099,-0.304402,0.609796,-0.153246
2013-01-04,1.281193,0.672607,0.346820,-0.040114
2013-01-05,-0.182106,1.181648,-0.662382,0.487758


In [33]:
# Yields a Series
df['A']

,A
2013-01-01,0.324547
2013-01-02,-0.368053
2013-01-03,-0.777946
2013-01-04,1.281193
2013-01-05,-0.182106
2013-01-06,0.416099


In [34]:
# Yields a DataFrame
df[['A', 'B']]

,A,B
2013-01-01,0.324547,-0.459218
2013-01-02,-0.368053,-1.739014
2013-01-03,-0.777946,-1.443906
2013-01-04,1.281193,0.672607
2013-01-05,-0.182106,1.181648
2013-01-06,0.416099,-0.304402


In [35]:
df[0:3]

,A,B,C,D
2013-01-01,0.324547,-0.459218,-0.300918,-0.226213
2013-01-02,-0.368053,-1.739014,1.516996,-1.274890
2013-01-03,-0.777946,-1.443906,-2.569005,0.324704


In [36]:
df["20130102":"20130104"]

,A,B,C,D
2013-01-02,-0.368053,-1.739014,1.516996,-1.274890
2013-01-03,-0.777946,-1.443906,-2.569005,0.324704
2013-01-04,1.281193,0.672607,0.346820,-0.040114


In [37]:
df.loc[dates[0]]

,2013-01-01
A,0.324547
B,-0.459218
C,-0.300918
D,-0.226213


In [38]:
df.loc[:, ["A", "B"]]

,A,B
2013-01-01,0.324547,-0.459218
2013-01-02,-0.368053,-1.739014
2013-01-03,-0.777946,-1.443906
2013-01-04,1.281193,0.672607
2013-01-05,-0.182106,1.181648
2013-01-06,0.416099,-0.304402


In [39]:
df[0:3]

,A,B,C,D
2013-01-01,0.324547,-0.459218,-0.300918,-0.226213
2013-01-02,-0.368053,-1.739014,1.516996,-1.274890
2013-01-03,-0.777946,-1.443906,-2.569005,0.324704


In [40]:
df.loc["20130102":"20130104", ["A", "B"]]

,A,B
2013-01-02,-0.368053,-1.739014
2013-01-03,-0.777946,-1.443906
2013-01-04,1.281193,0.672607


In [41]:
df.iloc[3]

,2013-01-04
A,1.281193
B,0.672607
C,0.346820
D,-0.040114


In [42]:
df.iloc[3:5, 0:2]

,A,B
2013-01-04,1.281193,0.672607
2013-01-05,-0.182106,1.181648


In [43]:
df.iloc[[1, 2, 4], [0, 2]]

,A,C
2013-01-02,-0.368053,1.516996
2013-01-03,-0.777946,-2.569005
2013-01-05,-0.182106,-0.662382


In [44]:
df.iloc[1:3, :]

,A,B,C,D
2013-01-02,-0.368053,-1.739014,1.516996,-1.274890
2013-01-03,-0.777946,-1.443906,-2.569005,0.324704


In [45]:
df.iloc[:, 1:3]

,B,C
2013-01-01,-0.459218,-0.300918
2013-01-02,-1.739014,1.516996
2013-01-03,-1.443906,-2.569005
2013-01-04,0.672607,0.346820
2013-01-05,1.181648,-0.662382
2013-01-06,-0.304402,0.609796


In [46]:
df.iloc[1, 1]

np.float64(-1.7390143488149934)

In [47]:
df.iat[1, 1]

np.float64(-1.7390143488149934)

In [48]:
df[df["A"] > 0]

,A,B,C,D
2013-01-01,0.324547,-0.459218,-0.300918,-0.226213
2013-01-04,1.281193,0.672607,0.346820,-0.040114
2013-01-06,0.416099,-0.304402,0.609796,-0.153246


In [49]:
df[df > 0]

,A,B,C,D
2013-01-01,0.324547,NaN,NaN,NaN
2013-01-02,NaN,NaN,1.516996,NaN
2013-01-03,NaN,NaN,NaN,0.324704
2013-01-04,1.281193,0.672607,0.346820,NaN
2013-01-05,NaN,1.181648,NaN,0.487758
2013-01-06,0.416099,NaN,0.609796,NaN


In [50]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2

,A,B,C,D,E
2013-01-01,0.324547,-0.459218,-0.300918,-0.226213,one
2013-01-02,-0.368053,-1.739014,1.516996,-1.274890,one
2013-01-03,-0.777946,-1.443906,-2.569005,0.324704,two
2013-01-04,1.281193,0.672607,0.346820,-0.040114,three
2013-01-05,-0.182106,1.181648,-0.662382,0.487758,four
2013-01-06,0.416099,-0.304402,0.609796,-0.153246,three


In [51]:
df2[df2["E"].isin(["two", "four"])]

,A,B,C,D,E
2013-01-03,-0.777946,-1.443906,-2.569005,0.324704,two
2013-01-05,-0.182106,1.181648,-0.662382,0.487758,four


In [52]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))
s1

,0
2013-01-02,1
2013-01-03,2
2013-01-04,3
2013-01-05,4
2013-01-06,5
2013-01-07,6


In [53]:
df["F"] = s1

In [54]:
df.at[dates[0], "A"] = 0

In [55]:
df.iat[0, 1] = 0

In [56]:
df.loc[:, "D"] = np.array([5] * len(df))

In [57]:
df

,A,B,C,D,F
2013-01-01,0.000000,0.000000,-0.300918,5.0,NaN
2013-01-02,-0.368053,-1.739014,1.516996,5.0,1.0
2013-01-03,-0.777946,-1.443906,-2.569005,5.0,2.0
2013-01-04,1.281193,0.672607,0.346820,5.0,3.0
2013-01-05,-0.182106,1.181648,-0.662382,5.0,4.0
2013-01-06,0.416099,-0.304402,0.609796,5.0,5.0


In [58]:
df2 = df.copy()
df2[df2 > 0] = -df2
df2

,A,B,C,D,F
2013-01-01,0.000000,0.000000,-0.300918,-5.0,NaN
2013-01-02,-0.368053,-1.739014,-1.516996,-5.0,-1.0
2013-01-03,-0.777946,-1.443906,-2.569005,-5.0,-2.0
2013-01-04,-1.281193,-0.672607,-0.346820,-5.0,-3.0
2013-01-05,-0.182106,-1.181648,-0.662382,-5.0,-4.0
2013-01-06,-0.416099,-0.304402,-0.609796,-5.0,-5.0


In [59]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1
df1

,A,B,C,D,F,E
2013-01-01,0.000000,0.000000,-0.300918,5.0,NaN,1.0
2013-01-02,-0.368053,-1.739014,1.516996,5.0,1.0,1.0
2013-01-03,-0.777946,-1.443906,-2.569005,5.0,2.0,NaN
2013-01-04,1.281193,0.672607,0.346820,5.0,3.0,NaN


In [60]:
df1.dropna(how="any")

,A,B,C,D,F,E
2013-01-02,-0.368053,-1.739014,1.516996,5.0,1.0,1.0


In [61]:
df1.fillna(value=5)

,A,B,C,D,F,E
2013-01-01,0.000000,0.000000,-0.300918,5.0,5.0,1.0
2013-01-02,-0.368053,-1.739014,1.516996,5.0,1.0,1.0
2013-01-03,-0.777946,-1.443906,-2.569005,5.0,2.0,5.0
2013-01-04,1.281193,0.672607,0.346820,5.0,3.0,5.0


In [62]:
pd.isna(df1)

,A,B,C,D,F,E
2013-01-01,False,False,False,False,True,False
2013-01-02,False,False,False,False,False,False
2013-01-03,False,False,False,False,False,True
2013-01-04,False,False,False,False,False,True


In [63]:
df.mean()

,0
A,0.061531
B,-0.272178
C,-0.176449
D,5.000000
F,3.000000


In [64]:
df.mean(axis=1)

,0
2013-01-01,1.174770
2013-01-02,1.081986
2013-01-03,0.441829
2013-01-04,2.060124
2013-01-05,1.867432
2013-01-06,2.144298


In [65]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)
s

,0
2013-01-01,NaN
2013-01-02,NaN
2013-01-03,1.0
2013-01-04,3.0
2013-01-05,5.0
2013-01-06,NaN


In [66]:
df.sub(s, axis="index")

,A,B,C,D,F
2013-01-01,NaN,NaN,NaN,NaN,NaN
2013-01-02,NaN,NaN,NaN,NaN,NaN
2013-01-03,-1.777946,-2.443906,-3.569005,4.0,1.0
2013-01-04,-1.718807,-2.327393,-2.653180,2.0,0.0
2013-01-05,-5.182106,-3.818352,-5.662382,0.0,-1.0
2013-01-06,NaN,NaN,NaN,NaN,NaN


In [67]:
df.agg(lambda x: np.mean(x) * 5.6)

,0
A,0.344574
B,-1.524196
C,-0.988114
D,28.000000
F,16.800000


In [68]:
df.transform(lambda x: x * 101.2)

,A,B,C,D,F
2013-01-01,0.000000,0.000000,-30.452921,506.0,NaN
2013-01-02,-37.246931,-175.988252,153.519991,506.0,101.2
2013-01-03,-78.728129,-146.123298,-259.983326,506.0,202.4
2013-01-04,129.656688,68.067822,35.098226,506.0,303.6
2013-01-05,-18.429150,119.582803,-67.033105,506.0,404.8
2013-01-06,42.109169,-30.805511,61.711329,506.0,506.0


In [69]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

,0
0,4
1,4
2,0
3,6
4,4
5,5
6,0
7,4
8,5
9,0


In [70]:
s.value_counts()

,count
4,4
0,3
5,2
6,1


In [71]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])
s.str.lower()

,0
0,a
1,b
2,c
3,aaba
4,baca
5,NaN
6,caba
7,dog
8,cat


In [72]:
df = pd.DataFrame(np.random.randn(10, 4))
df

,0,1,2,3
0,-0.464712,0.006296,0.477150,-1.122259
1,-0.661906,-1.007509,0.782036,-1.443713
2,0.096011,0.571526,0.839199,0.659300
3,1.803541,0.088893,1.552478,1.811620
4,-0.867352,-1.766128,-0.116725,-1.472961
5,0.858115,-0.160310,1.520083,-1.197461
6,0.013984,1.976490,-0.971399,-0.911868
7,0.576999,-0.402929,-1.285618,-0.638906
8,1.300713,0.340065,-0.134402,0.595550
9,0.244045,1.638832,-0.249040,0.374616


In [73]:
pieces = [df[:3], df[3:7], df[7:]]

In [74]:
pd.concat(pieces)

,0,1,2,3
0,-0.464712,0.006296,0.477150,-1.122259
1,-0.661906,-1.007509,0.782036,-1.443713
2,0.096011,0.571526,0.839199,0.659300
3,1.803541,0.088893,1.552478,1.811620
4,-0.867352,-1.766128,-0.116725,-1.472961
5,0.858115,-0.160310,1.520083,-1.197461
6,0.013984,1.976490,-0.971399,-0.911868
7,0.576999,-0.402929,-1.285618,-0.638906
8,1.300713,0.340065,-0.134402,0.595550
9,0.244045,1.638832,-0.249040,0.374616


In [75]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [76]:
left

,key,lval
0,foo,1
1,foo,2


In [77]:
right

,key,rval
0,foo,4
1,foo,5


In [78]:
pd.merge(left, right, on="key")

,key,lval,rval
0,foo,1,4
1,foo,1,5
2,foo,2,4
3,foo,2,5


In [79]:
left = pd.DataFrame({"key": ["foo", "bar"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "bar"], "rval": [4, 5]})

In [80]:
left

,key,lval
0,foo,1
1,bar,2


In [81]:
right

,key,rval
0,foo,4
1,bar,5


In [82]:
pd.merge(left, right, on="key")

,key,lval,rval
0,foo,1,4
1,bar,2,5


In [83]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)
df

,A,B,C,D
0,foo,one,0.203394,-0.082586
1,bar,one,-1.241008,-0.898190
2,foo,two,-1.751337,-1.443832
3,bar,three,0.419974,0.748046
4,foo,two,0.758346,0.478166
5,bar,two,-0.128236,-0.003958
6,foo,one,0.294490,0.012455
7,foo,three,1.587021,-0.603809


In [84]:
df.groupby("A")[["C", "D"]].sum()

,C,D
A,,
bar,-0.949270,-0.154103
foo,1.091915,-1.639606


In [85]:
df.groupby(["A", "B"]).sum()
#

C         D
A   B                        
bar one   -1.241008 -0.898190
    three  0.419974  0.748046
    two   -0.128236 -0.003958
foo one    0.497884 -0.070131
    three  1.587021 -0.603809
    two   -0.992990 -0.965666

In [86]:
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]

In [87]:
index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])

In [88]:
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])
df

A         B
first second                    
bar   one     0.422299  1.393107
      two    -0.252337 -1.158166
baz   one     0.937593 -0.059486
      two    -0.314101 -0.180424
foo   one     0.140406  0.415313
      two     0.755957  1.745431
qux   one     1.422660  1.128686
      two     2.367681  0.395474

In [89]:
df2 = df[:4]
df2

A         B
first second                    
bar   one     0.422299  1.393107
      two    -0.252337 -1.158166
baz   one     0.937593 -0.059486
      two    -0.314101 -0.180424

In [90]:
stacked = df.stack()
stacked

first  second   
bar    one     A    0.422299
               B    1.393107
       two     A   -0.252337
               B   -1.158166
baz    one     A    0.937593
               B   -0.059486
       two     A   -0.314101
               B   -0.180424
foo    one     A    0.140406
               B    0.415313
       two     A    0.755957
               B    1.745431
qux    one     A    1.422660
               B    1.128686
       two     A    2.367681
               B    0.395474
dtype: float64

In [91]:
stacked.unstack()

A         B
first second                    
bar   one     0.422299  1.393107
      two    -0.252337 -1.158166
baz   one     0.937593 -0.059486
      two    -0.314101 -0.180424
foo   one     0.140406  0.415313
      two     0.755957  1.745431
qux   one     1.422660  1.128686
      two     2.367681  0.395474

In [92]:
stacked.unstack(1)

second        one       two
first                      
bar   A  0.422299 -0.252337
      B  1.393107 -1.158166
baz   A  0.937593 -0.314101
      B -0.059486 -0.180424
foo   A  0.140406  0.755957
      B  0.415313  1.745431
qux   A  1.422660  2.367681
      B  1.128686  0.395474

In [93]:
stacked.unstack(0)

first          bar       baz       foo       qux
second                                          
one    A  0.422299  0.937593  0.140406  1.422660
       B  1.393107 -0.059486  0.415313  1.128686
two    A -0.252337 -0.314101  0.755957  2.367681
       B -1.158166 -0.180424  1.745431  0.395474

In [94]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)
df

,A,B,C,D,E
0,one,A,foo,1.575080,0.018923
1,one,B,foo,-0.150147,1.893466
2,two,C,foo,0.905720,0.837410
3,three,A,bar,0.119688,0.558165
4,one,B,bar,0.091600,0.638445
5,one,C,bar,-0.338236,0.969173
6,two,A,foo,-0.581277,0.232067
7,three,B,foo,0.259726,1.331875
8,one,C,foo,0.096536,0.052589
9,one,A,bar,0.401697,-0.215478


In [95]:
pd.pivot_table(df, values="D", index=["A", "B"], columns=["C"])

C             bar       foo
A     B                    
one   A  0.401697  1.575080
      B  0.091600 -0.150147
      C -0.338236  0.096536
three A  0.119688       NaN
      B       NaN  0.259726
      C -0.482749       NaN
two   A       NaN -0.581277
      B  0.926902       NaN
      C       NaN  0.905720

In [96]:
rng = pd.date_range("1/1/2012", periods=100, freq="S")
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)
ts

/tmp/ipython-input-4089086473.py:1: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  rng = pd.date_range("1/1/2012", periods=100, freq="S")


,0
2012-01-01 00:00:00,49
2012-01-01 00:00:01,130
2012-01-01 00:00:02,44
2012-01-01 00:00:03,59
2012-01-01 00:00:04,414
...,...
2012-01-01 00:01:35,48
2012-01-01 00:01:36,307
2012-01-01 00:01:37,331
2012-01-01 00:01:38,263


In [97]:
ts.resample("5Min").sum()

,0
2012-01-01,24591


In [98]:
rng = pd.date_range("3/6/2012 00:00", periods=5, freq="D")
ts = pd.Series(np.random.randn(len(rng)), rng)
ts

,0
2012-03-06,-0.185756
2012-03-07,0.369480
2012-03-08,-0.742609
2012-03-09,0.831865
2012-03-10,0.290428


In [99]:
ts_utc = ts.tz_localize("UTC")
ts_utc

,0
2012-03-06 00:00:00+00:00,-0.185756
2012-03-07 00:00:00+00:00,0.369480
2012-03-08 00:00:00+00:00,-0.742609
2012-03-09 00:00:00+00:00,0.831865
2012-03-10 00:00:00+00:00,0.290428


In [100]:
ts_utc.tz_convert("US/Eastern")

,0
2012-03-05 19:00:00-05:00,-0.185756
2012-03-06 19:00:00-05:00,0.369480
2012-03-07 19:00:00-05:00,-0.742609
2012-03-08 19:00:00-05:00,0.831865
2012-03-09 19:00:00-05:00,0.290428


In [101]:
rng

DatetimeIndex(['2012-03-06', '2012-03-07', '2012-03-08', '2012-03-09',
               '2012-03-10'],
              dtype='datetime64[ns]', freq='D')

In [102]:
rng + pd.offsets.BusinessDay(5)

DatetimeIndex(['2012-03-13', '2012-03-14', '2012-03-15', '2012-03-16',
               '2012-03-16'],
              dtype='datetime64[ns]', freq=None)

In [103]:
df = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5, 6],
        "raw_grade": ["a", "b", "b", "a", "a", "e"],
    }
)
df

,id,raw_grade
0,1,a
1,2,b
2,3,b
3,4,a
4,5,a
5,6,e


In [104]:
df["grade"] = df["raw_grade"].astype("category")
df["grade"]

,grade
0,a
1,b
2,b
3,a
4,a
5,e


In [105]:
df

,id,raw_grade,grade
0,1,a,a
1,2,b,b
2,3,b,b
3,4,a,a
4,5,a,a
5,6,e,e


In [107]:
new_categories = ["very good", "good", "very bad"]
df["grade"] = df["grade"].cat.rename_categories(new_categories)
df["grade"]

,grade
0,NaN
1,NaN
2,NaN
3,NaN
4,NaN
5,NaN


In [108]:
df["grade"] = df["grade"].cat.set_categories(
    ["very bad", "bad", "medium", "good", "very good"]
)
df["grade"]

,grade
0,NaN
1,NaN
2,NaN
3,NaN
4,NaN
5,NaN
