<a href="https://colab.research.google.com/github/ankitkparashar/python/blob/main/CSML/Module1/Week1/Jiao_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello World!')

hello_world_string = "Hello World!"
print(hello_world_string)

Hello World!
Hello World!


In [2]:
print("Variable Assignment")

a0_var = 3
A0_var = 4

print("Variable a0_var assigned value:", a0_var)
print("Variable A0_var assigned value:", A0_var)

Variable Assignment
Variable a0_var assigned value: 3
Variable A0_var assigned value: 4


In [3]:
x = 2
print("The type of x is:", type(x))

y = 2.5
print("The type of y is:", type(y))

z = "Hello World!"
print("The type of z is:", type(z))

The type of x is: <class 'int'>
The type of y is: <class 'float'>
The type of z is: <class 'str'>


In [4]:
#Addition, subtraction, multiplication, exponentiation

print("x + 3 is", x + 3)
print("x - 15 is", x - 15)
print("x * 3 is", x * 3)
print("x / 2 is", x / 2)
print("x // 2 (floor division) is", x // 2)
print("x mod 2 (remainder) is", x % 2)
print("x ** 3 (exponentiation) is", x ** 3)

x += 1
print("x += 1 is", x)
x *= 2
print("x *= 2 is", x)

x + 3 is 5
x - 15 is -13
x * 3 is 6
x / 2 is 1.0
x // 2 (floor division) is 1
x mod 2 (remainder) is 0
x ** 3 (exponentiation) is 8
x += 1 is 3
x *= 2 is 6


In [5]:
c = x + y
print("c has the value:", c, "and the type:", type(c))

d = x * y
print("d has the value:", d, "and the type:", type(d))

c has the value: 8.5 and the type: <class 'float'>
d has the value: 15.0 and the type: <class 'float'>


In [6]:
print("Booleans")

t = True
f = False

print("The type of t is:", type(t))
print("The type of f is:", type(f))

Booleans
The type of t is: <class 'bool'>
The type of f is: <class 'bool'>


In [7]:
print(t and f)
print(t or f)
print(not t)
print(t != f)
print(f == f)

False
True
False
True
True


In [8]:
import numpy as np

In [9]:
x = np.arange(0, 11, 1)
print("Integer spaced:", x)

x_new = np.linspace(0, 10, 21)
print("Linearly/Float spaced:", x_new)

#Array of ones
ones = np.ones(10)
print("Array of ones:", ones)

#Matrices
mat_a = np.array([[1, 2], [3, 4]])
print("Matrix:", mat_a)

#Identity Matrix
print(np.eye(3))

Integer spaced: [ 0  1  2  3  4  5  6  7  8  9 10]
Linearly/Float spaced: [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
Array of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of zeros: [[1 2]
 [3 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
import pandas as pd

In [11]:
#Download titanic set
titanic_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

print(titanic_df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [12]:
x_array = np.arange(0, 11, 1)
print("Length of x_array is: {}".format(len(x_array)))

Length of x_array is: 11


In [13]:
x_array[3]

np.int64(3)

In [14]:
x_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
print(x_array[3:7])

[3 4 5 6]


In [18]:
#w = A * (np.exp(-t / tau) - 1 + (t / tau))

### 10 Minutes to Pandas

In [21]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [22]:
dates = pd.date_range('20130101', periods=6)
print(dates)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [23]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)

                   A         B         C         D
2013-01-01  1.773072  0.502808 -0.046345 -0.543808
2013-01-02  0.861458  0.386211 -0.463119  1.426372
2013-01-03  0.341793  0.013815 -1.086965  0.221109
2013-01-04 -0.506121 -0.496150  0.684114  1.156618
2013-01-05  1.042796  0.266330  0.840778 -1.589101
2013-01-06  0.987232 -0.379183  0.088517 -1.714857


In [24]:
df2 = pd.DataFrame({'A': 1.0,
                    "B": pd.Timestamp('20130102'),
                    "C": pd.Series(1, index=list(range(4)), dtype='float32'),
                    "D": np.array([3] * 4, dtype='int32'),
                    "E": pd.Categorical(["test", "train", "test", "train"]),
                    "F": 'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [25]:
df2.dtypes

,0
A,float64
B,datetime64[s]
C,float32
D,int32
E,category
F,object


In [27]:
df.head()

,A,B,C,D
2013-01-01,1.773072,0.502808,-0.046345,-0.543808
2013-01-02,0.861458,0.386211,-0.463119,1.426372
2013-01-03,0.341793,0.013815,-1.086965,0.221109
2013-01-04,-0.506121,-0.496150,0.684114,1.156618
2013-01-05,1.042796,0.266330,0.840778,-1.589101


In [28]:
df.tail(3)

,A,B,C,D
2013-01-04,-0.506121,-0.496150,0.684114,1.156618
2013-01-05,1.042796,0.266330,0.840778,-1.589101
2013-01-06,0.987232,-0.379183,0.088517,-1.714857


In [29]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [30]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [31]:
df.to_numpy()

array([[ 1.7730716 ,  0.50280768, -0.04634524, -0.54380789],
       [ 0.86145756,  0.3862112 , -0.46311877,  1.42637223],
       [ 0.34179323,  0.01381454, -1.08696464,  0.22110905],
       [-0.50612053, -0.49615008,  0.68411375,  1.15661834],
       [ 1.04279629,  0.26633025,  0.84077793, -1.58910129],
       [ 0.98723232, -0.37918335,  0.08851664, -1.71485742]])

In [32]:
df2.dtypes

,0
A,float64
B,datetime64[s]
C,float32
D,int32
E,category
F,object


In [33]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [34]:
df.describe()

,A,B,C,D
count,6.000000,6.000000,6.000000,6.000000
mean,0.750038,0.048972,0.002830,-0.173944
std,0.767539,0.411984,0.718446,1.341742
min,-0.506121,-0.496150,-1.086965,-1.714857
25%,0.471709,-0.280934,-0.358925,-1.327778
50%,0.924345,0.140072,0.021086,-0.161349
75%,1.028905,0.356241,0.535214,0.922741
max,1.773072,0.502808,0.840778,1.426372


In [35]:
df.T

,2013-01-01,2013-01-02,2013-01-03,2013-01-04,2013-01-05,2013-01-06
A,1.773072,0.861458,0.341793,-0.506121,1.042796,0.987232
B,0.502808,0.386211,0.013815,-0.496150,0.266330,-0.379183
C,-0.046345,-0.463119,-1.086965,0.684114,0.840778,0.088517
D,-0.543808,1.426372,0.221109,1.156618,-1.589101,-1.714857


In [36]:
df.sort_index(axis=1, ascending=False)

,D,C,B,A
2013-01-01,-0.543808,-0.046345,0.502808,1.773072
2013-01-02,1.426372,-0.463119,0.386211,0.861458
2013-01-03,0.221109,-1.086965,0.013815,0.341793
2013-01-04,1.156618,0.684114,-0.496150,-0.506121
2013-01-05,-1.589101,0.840778,0.266330,1.042796
2013-01-06,-1.714857,0.088517,-0.379183,0.987232


In [39]:
df.sort_values(by='B')

,A,B,C,D
2013-01-04,-0.506121,-0.496150,0.684114,1.156618
2013-01-06,0.987232,-0.379183,0.088517,-1.714857
2013-01-03,0.341793,0.013815,-1.086965,0.221109
2013-01-05,1.042796,0.266330,0.840778,-1.589101
2013-01-02,0.861458,0.386211,-0.463119,1.426372
2013-01-01,1.773072,0.502808,-0.046345,-0.543808


In [40]:
# Yields a Series
df['A']

,A
2013-01-01,1.773072
2013-01-02,0.861458
2013-01-03,0.341793
2013-01-04,-0.506121
2013-01-05,1.042796
2013-01-06,0.987232


In [41]:
# Yields a DataFrame
df[['A', 'B']]

,A,B
2013-01-01,1.773072,0.502808
2013-01-02,0.861458,0.386211
2013-01-03,0.341793,0.013815
2013-01-04,-0.506121,-0.496150
2013-01-05,1.042796,0.266330
2013-01-06,0.987232,-0.379183


In [42]:
df[0:3]

,A,B,C,D
2013-01-01,1.773072,0.502808,-0.046345,-0.543808
2013-01-02,0.861458,0.386211,-0.463119,1.426372
2013-01-03,0.341793,0.013815,-1.086965,0.221109


In [43]:
df["20130102":"20130104"]

,A,B,C,D
2013-01-02,0.861458,0.386211,-0.463119,1.426372
2013-01-03,0.341793,0.013815,-1.086965,0.221109
2013-01-04,-0.506121,-0.496150,0.684114,1.156618


In [44]:
df.loc[dates[0]]

,2013-01-01
A,1.773072
B,0.502808
C,-0.046345
D,-0.543808


In [46]:
df.loc[:, ["A", "B"]]

,A,B
2013-01-01,1.773072,0.502808
2013-01-02,0.861458,0.386211
2013-01-03,0.341793,0.013815
2013-01-04,-0.506121,-0.496150
2013-01-05,1.042796,0.266330
2013-01-06,0.987232,-0.379183


In [47]:
df[0:3]

,A,B,C,D
2013-01-01,1.773072,0.502808,-0.046345,-0.543808
2013-01-02,0.861458,0.386211,-0.463119,1.426372
2013-01-03,0.341793,0.013815,-1.086965,0.221109


In [48]:
df.loc["20130102":"20130104", ["A", "B"]]

,A,B
2013-01-02,0.861458,0.386211
2013-01-03,0.341793,0.013815
2013-01-04,-0.506121,-0.496150


In [49]:
df.iloc[3]

,2013-01-04
A,-0.506121
B,-0.496150
C,0.684114
D,1.156618


In [50]:
df.iloc[3:5, 0:2]

,A,B
2013-01-04,-0.506121,-0.49615
2013-01-05,1.042796,0.26633


In [51]:
df.iloc[[1, 2, 4], [0, 2]]

,A,C
2013-01-02,0.861458,-0.463119
2013-01-03,0.341793,-1.086965
2013-01-05,1.042796,0.840778


In [52]:
df.iloc[1:3, :]

,A,B,C,D
2013-01-02,0.861458,0.386211,-0.463119,1.426372
2013-01-03,0.341793,0.013815,-1.086965,0.221109


In [53]:
df.iloc[:, 1:3]

,B,C
2013-01-01,0.502808,-0.046345
2013-01-02,0.386211,-0.463119
2013-01-03,0.013815,-1.086965
2013-01-04,-0.496150,0.684114
2013-01-05,0.266330,0.840778
2013-01-06,-0.379183,0.088517


In [54]:
df.iloc[1, 1]

np.float64(0.38621120153919003)

In [55]:
df.iat[1, 1]

np.float64(0.38621120153919003)

In [56]:
df[df["A"] > 0]

,A,B,C,D
2013-01-01,1.773072,0.502808,-0.046345,-0.543808
2013-01-02,0.861458,0.386211,-0.463119,1.426372
2013-01-03,0.341793,0.013815,-1.086965,0.221109
2013-01-05,1.042796,0.266330,0.840778,-1.589101
2013-01-06,0.987232,-0.379183,0.088517,-1.714857


In [57]:
df[df > 0]

,A,B,C,D
2013-01-01,1.773072,0.502808,NaN,NaN
2013-01-02,0.861458,0.386211,NaN,1.426372
2013-01-03,0.341793,0.013815,NaN,0.221109
2013-01-04,NaN,NaN,0.684114,1.156618
2013-01-05,1.042796,0.266330,0.840778,NaN
2013-01-06,0.987232,NaN,0.088517,NaN


In [58]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2

,A,B,C,D,E
2013-01-01,1.773072,0.502808,-0.046345,-0.543808,one
2013-01-02,0.861458,0.386211,-0.463119,1.426372,one
2013-01-03,0.341793,0.013815,-1.086965,0.221109,two
2013-01-04,-0.506121,-0.496150,0.684114,1.156618,three
2013-01-05,1.042796,0.266330,0.840778,-1.589101,four
2013-01-06,0.987232,-0.379183,0.088517,-1.714857,three


In [59]:
df2[df2["E"].isin(["two", "four"])]

,A,B,C,D,E
2013-01-03,0.341793,0.013815,-1.086965,0.221109,two
2013-01-05,1.042796,0.266330,0.840778,-1.589101,four
