<a href="https://colab.research.google.com/github/ankitkparashar/python/blob/main/CSML/Module1/Week1/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
a = np.array([2, 3, 4])

In [10]:
a

array([2, 3, 4])

In [11]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [12]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [13]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [14]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [18]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [19]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
x = np.linspace(0, 2*np.pi, 100)
f = np.sin(x)

In [21]:
a = np.arange(6)

In [22]:
a

array([0, 1, 2, 3, 4, 5])

In [23]:
b = np.arange(12).reshape(4, 3)

In [24]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
c = np.arange(24).reshape(2, 3, 4)

In [26]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [28]:
c = a - b

In [29]:
c

array([20, 29, 38, 47])

In [30]:
b ** 2

array([0, 1, 4, 9])

In [31]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [32]:
a < 35

array([ True,  True, False, False])

In [33]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

In [34]:
A * B

array([[2, 0],
       [0, 4]])

In [35]:
A @ B

array([[5, 4],
       [3, 4]])

In [36]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [37]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [38]:
rg

Generator(PCG64) at 0x79A34597C580

In [39]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [40]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
b.dtype.name

'float64'

In [41]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [42]:
c.dtype.name

'float64'

In [43]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [44]:
d.dtype.name

'complex128'

In [45]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [46]:
a.sum()

np.float64(3.1057109529998157)

In [47]:
a.min()

np.float64(0.027559113243068367)

In [48]:
a.max()

np.float64(0.8277025938204418)

In [49]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [51]:
b.min(axis=1)

array([0, 4, 8])

In [52]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [53]:
B = np.arange(3)
B

array([0, 1, 2])

In [54]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [55]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [56]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [57]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [58]:
a[2]

np.int64(8)

In [59]:
a[2:5]

array([ 8, 27, 64])

In [60]:
a[:6:2]

array([ 0,  8, 64])

In [61]:
a[:6:2]= 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [62]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [63]:
for i in a:
  print(i ** (1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [64]:
def f(x, y):
  return 10 * x + y

In [65]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [66]:
b[2, 3]

np.int64(23)

In [67]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [68]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [69]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [70]:
b[-1]

array([40, 41, 42, 43])

In [71]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [72]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [73]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [74]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [75]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [76]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [77]:
a.shape

(3, 4)

In [78]:
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [79]:
a.reshape(6, 2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [80]:
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [81]:
a.resize((2, 6))

In [82]:
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [83]:
a.reshape(3, -1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [84]:
a = np.floor(10*rg.random((2, 2)))
a

array([[9., 7.],
       [5., 2.]])

In [85]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[1., 9.],
       [5., 1.]])

In [86]:
np.vstack((a, b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [87]:
np.hstack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [88]:
np.column_stack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [89]:
a = np.array([4., 2.])
b = np.array([3., 8.])

In [90]:
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [91]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [92]:
a[:, np.newaxis]

array([[4.],
       [2.]])

In [93]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4., 3.],
       [2., 8.]])

In [94]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4., 3.],
       [2., 8.]])

In [95]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [96]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [97]:
np.hsplit(a, 3)

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]),
 array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

In [98]:
np.hsplit(a, (3, 4))

[array([[6., 7., 6.],
        [8., 5., 5.]]),
 array([[9.],
        [7.]]),
 array([[0., 5., 4., 0., 6., 8., 5., 2.],
        [1., 8., 6., 7., 1., 8., 1., 0.]])]

In [99]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a
b is a

True

In [100]:
def f(x):
  print(id(x))

In [101]:
id(a)

133742154815344

In [102]:
f(a)

133742154815344


In [103]:
c = a.view()
c is a

False

In [104]:
c.base is a

True

In [105]:
c.flags.owndata

False

In [106]:
c = c.reshape((2, 6))

In [107]:
a.shape

(3, 4)

In [108]:
c[0, 4] = 1234

In [109]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [110]:
s = a[:, 1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [111]:
d = a.copy()
d is a

False

In [112]:
d.base is a

False

In [113]:
d[0, 0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [114]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a

In [115]:
a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])
a[i]

array([ 1,  1,  9, 64, 25])

In [116]:
j = np.array([[3, 4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [117]:
palette = np.array([[0, 0, 0],
                    [255, 0, 0],
                    [0, 255, 0],
                    [0, 0, 255],
                    [255, 255, 255]])

In [118]:
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [119]:
a = np.arange(12).reshape(3, 4)

In [120]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
i = np.array([[0, 1], [1, 2]])
j = np.array([[2, 1], [3, 3]])

In [122]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [123]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [124]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [125]:
l = (i, j)
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [126]:
s = np.array([i, j])

In [128]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [129]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.stack((a, b), axis=1)
print(c)
print(c.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)
