<a href="https://colab.research.google.com/github/ankitkparashar/python/blob/main/CSML/Module1/Week1/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np

In [50]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
a.shape

(3, 5)

In [52]:
a.ndim

2

In [53]:
a.dtype.name

'int64'

In [54]:
a.itemsize

8

In [55]:
a.size

15

In [56]:
type(a)

numpy.ndarray

In [57]:
a = np.array([2, 3, 4])

In [58]:
a

array([2, 3, 4])

In [59]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [60]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [61]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [62]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [64]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [65]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [66]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [67]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [68]:
x = np.linspace(0, 2*np.pi, 100)
f = np.sin(x)

In [69]:
a = np.arange(6)

In [70]:
a

array([0, 1, 2, 3, 4, 5])

In [71]:
b = np.arange(12).reshape(4, 3)

In [72]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
c = np.arange(24).reshape(2, 3, 4)

In [74]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [76]:
c = a - b

In [77]:
c

array([20, 29, 38, 47])

In [78]:
b ** 2

array([0, 1, 4, 9])

In [79]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [80]:
a < 35

array([ True,  True, False, False])

In [81]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

In [82]:
A * B

array([[2, 0],
       [0, 4]])

In [83]:
A @ B

array([[5, 4],
       [3, 4]])

In [84]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [85]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [86]:
rg

Generator(PCG64) at 0x7BDEF28F2B20

In [87]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [88]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
b.dtype.name

'float64'

In [89]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [90]:
c.dtype.name

'float64'

In [91]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [92]:
d.dtype.name

'complex128'

In [93]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [94]:
a.sum()

np.float64(3.1057109529998157)

In [95]:
a.min()

np.float64(0.027559113243068367)

In [96]:
a.max()

np.float64(0.8277025938204418)

In [97]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [99]:
b.min(axis=1)

array([0, 4, 8])

In [100]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [101]:
B = np.arange(3)
B

array([0, 1, 2])

In [103]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [104]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [105]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [106]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [107]:
a[2]

np.int64(8)

In [108]:
a[2:5]

array([ 8, 27, 64])

In [109]:
a[:6:2]

array([ 0,  8, 64])

In [110]:
a[:6:2]= 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [111]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [112]:
for i in a:
  print(i ** (1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [113]:
def f(x, y):
  return 10 * x + y

In [114]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [115]:
b[2, 3]

np.int64(23)

In [116]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [117]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [118]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [119]:
b[-1]

array([40, 41, 42, 43])

In [120]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [121]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [122]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [123]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [124]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [125]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [126]:
a.shape

(3, 4)

In [127]:
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [128]:
a.reshape(6, 2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [129]:
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [130]:
a.resize((2, 6))

In [131]:
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [132]:
a.reshape(3, -1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [137]:
a = np.floor(10*rg.random((2, 2)))
a

array([[6., 9.],
       [0., 5.]])

In [138]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[4., 0.],
       [6., 8.]])

In [139]:
np.vstack((a, b))

array([[6., 9.],
       [0., 5.],
       [4., 0.],
       [6., 8.]])

In [140]:
np.hstack((a, b))

array([[6., 9., 4., 0.],
       [0., 5., 6., 8.]])

In [141]:
np.column_stack((a, b))

array([[6., 9., 4., 0.],
       [0., 5., 6., 8.]])

In [142]:
a = np.array([4., 2.])
b = np.array([3., 8.])

In [143]:
np.column_stack((a, b))

array([[4., 3.],
       [2., 8.]])

In [144]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [145]:
a[:, np.newaxis]

array([[4.],
       [2.]])

In [146]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4., 3.],
       [2., 8.]])

In [147]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4., 3.],
       [2., 8.]])

In [148]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [149]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[5., 2., 8., 5., 5., 7., 1., 8., 6., 7., 1., 8.],
       [1., 0., 8., 8., 8., 4., 2., 0., 6., 7., 8., 2.]])

In [150]:
np.hsplit(a, 3)

[array([[5., 2., 8., 5.],
        [1., 0., 8., 8.]]),
 array([[5., 7., 1., 8.],
        [8., 4., 2., 0.]]),
 array([[6., 7., 1., 8.],
        [6., 7., 8., 2.]])]

In [151]:
np.hsplit(a, (3, 4))

[array([[5., 2., 8.],
        [1., 0., 8.]]),
 array([[5.],
        [8.]]),
 array([[5., 7., 1., 8., 6., 7., 1., 8.],
        [8., 4., 2., 0., 6., 7., 8., 2.]])]

In [152]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a
b is a

True

In [153]:
def f(x):
  print(id(x))

In [154]:
id(a)

136197480436272

In [155]:
f(a)

136197480436272


In [156]:
c = a.view()
c is a

False

In [157]:
c.base is a

True

In [158]:
c.flags.owndata

False

In [159]:
c = c.reshape((2, 6))

In [160]:
a.shape

(3, 4)

In [161]:
c[0, 4] = 1234

In [162]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [163]:
s = a[:, 1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [164]:
d = a.copy()
d is a

False

In [165]:
d.base is a

False

In [166]:
d[0, 0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [167]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a

In [168]:
a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])
a[i]

array([ 1,  1,  9, 64, 25])

In [169]:
j = np.array([[3, 4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [170]:
palette = np.array([[0, 0, 0],
                    [255, 0, 0],
                    [0, 255, 0],
                    [0, 0, 255],
                    [255, 255, 255]])

In [171]:
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [172]:
a = np.arange(12).reshape(3, 4)

In [173]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [175]:
i = np.array([[0, 1], [1, 2]])
j = np.array([[2, 1], [3, 3]])

In [176]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [177]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [178]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [179]:
l = (i, j)
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [180]:
s = np.array([i, j])

In [181]:
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [182]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])