In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [2]:
iris = load_iris()

In [3]:
type(iris.data)

numpy.ndarray

In [4]:
iris.data.shape

(150, 4)

In [5]:
iris.data[5, :]

array([5.4, 3.9, 1.7, 0.4])

In [6]:
iris.data[:5, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [7]:
iris.target.shape

(150,)

In [8]:
iris.target[:5]

array([0, 0, 0, 0, 0])

In [9]:
len(iris.target == 0)

150

In [10]:
np.array(iris.target == 1).astype(np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
X = iris.data[:, (2, 3)]
y = (iris.target == 0).astype(np.int)

In [12]:
type(y)

numpy.ndarray

In [13]:
len(y)

150

In [14]:
iris.target[iris.target == 1]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [15]:
per_clf = Perceptron()

In [16]:
per_clf.fit(X, y)

Perceptron()

In [17]:
y_pred = per_clf.predict([[2, 0.5]])

In [18]:
y_pred

array([0])

In [19]:
# pip install tensorflow

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
tf.__version__

In [ ]:
keras.__version__

In [ ]:
fashion_mnist = keras.datasets.fashion_mnist

In [ ]:
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()

In [ ]:
type(X_train_full)

In [ ]:
type(y_train_full)

In [ ]:
X_train_full.shape

In [ ]:
X_train_full.dtype

In [ ]:
X_valid, X_train = X_train_full[:5000] / 255.0, X_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]
X_test = X_test / 255.0

In [ ]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", 
              "Shirt", "Sneaker", "Bag", "Ankle Boot"]

In [ ]:
class_names[y_train[0]]

In [ ]:
X_train[0].shape

In [ ]:
X_train[0].reshape(-1, 28*28).shape

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28, 28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))

In [ ]:
model.summary()

In [ ]:
model.layers

In [ ]:
hidden_1 = model.layers[1]

In [ ]:
hidden_1.name

In [ ]:
model.get_layer('dense') is hidden_1

In [ ]:
weights, biases = hidden_1.get_weights()

In [ ]:
weights

In [ ]:
weights.shape

In [ ]:
biases

In [ ]:
biases.shape

In [ ]:
model.compile(loss="sparse_categorical_crossentropy", optimizer = "sgd", 
             metrics = ["accuracy"])

In [ ]:
history = model.fit(X_train, y_train, epochs=30, 
                    validation_data = (X_valid, y_valid))

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
pd.DataFrame(history.history)

In [ ]:
pd.DataFrame(history.history).plot(figsize = (8, 5))
plt.grid(True)
plt.gca().set_ylim(0, 1)
plt.show()

In [ ]:
history.params

In [ ]:
history

In [ ]:
history.epoch

In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
X_new = X_test[:3]

In [ ]:
y_proba = model.predict(X_new)
y_proba.round(2)

In [ ]:
y_pred = model.predict_classes(X_new)
y_pred

In [ ]:
np.array(class_names)[y_pred]

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
housing = fetch_california_housing()

In [ ]:
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, 
                                                              housing.target)

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, 
                                                      y_train_full)

In [ ]:
type(X_train)

In [ ]:
X_train.shape, X_test.shape

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [ ]:
model = keras.models.Sequential([keras.layers.Dense(30, activation = "relu", 
                                                   input_shape = X_train.shape[1:]), 
                                keras.layers.Dense(1)])

In [ ]:
model.compile(loss="mean_squared_error", optimizer = "sgd")

In [ ]:
history = model.fit(X_train, y_train, epochs=20, 
                   validation_data=(X_valid, y_valid))

In [ ]:
mse_test = model.evaluate(X_test, y_test)

In [ ]:
X_new = X_test[:3]
y_pred = model.predict(X_new)

In [ ]:
y_pred

In [ ]:
y_test[:3]

### Deep-Wide Network Implementation

In [ ]:
input_ = keras.layers.Input(shape=X_train.shape[1:])
hidden_1 = keras.layers.Dense(30, activation = "relu")(input_)
hidden_2 = keras.layers.Dense(30, activation = "relu")(hidden_1)
concat = keras.layers.Concatenate()([input_, hidden_2])
output = keras.layers.Dense(1)(concat)
model = keras.Model(inputs = [input_], outputs = [output])

In [ ]:
model.summary()

In [ ]:
keras.utils.plot_model(model, "deep-wide-model.png")

In [ ]:
#pip install pydot

In [ ]:
#pip install graphviz

In [ ]:
keras.utils.plot_model(model, "deep-wide-model.png", show_shapes=True)

In [ ]:
model.compile(loss="mean_squared_error", optimizer = "sgd")

In [ ]:
history = model.fit(X_train, y_train, epochs=20, 
                   validation_data=(X_valid, y_valid))

In [ ]:
input_A = keras.layers.Input(shape = [5], name = "wide_input")
input_B = keras.layers.Input(shape = [6], name = "deep_input")
hidden1 = keras.layers.Dense(30, activation = "relu")(input_B)
hidden2 = keras.layers.Dense(30, activation = "relu")(hidden1)
concat = keras.layers.concatenate([input_A, hidden2])
output = keras.layers.Dense(1, name = "output")(concat)
model = keras.Model(inputs = [input_A, input_B], outputs = [output])

In [ ]:
model.compile(loss = "mse", optimizer = keras.optimizers.SGD(lr = 1e-3))

In [ ]:
X_train_A, X_train_B = X_train[:, :5], X_train[:, 2:]
X_valid_A, X_valid_B = X_valid[:, :5], X_valid[:, 2:]
X_test_A, X_test_B = X_test[:, :5], X_test[:, 2:]
X_new_A, X_new_B = X_test_A[:3], X_test_B[:3]

In [ ]:
history = model.fit((X_train_A, X_train_B), y_train, epochs=20, 
                   validation_data = ((X_valid_A, X_valid_B), y_valid))
mse_test = model.evaluate((X_test_A, X_test_B), y_test)
y_pred = model.predict((X_new_A, X_new_B))

In [ ]:
class WideAndDeepModel(keras.Model):
    def __init__(self, units = 30, activation = "relu", **kwargs):
        super().__init__(**kwargs)
        self.hidden1 = keras.layers.Dense(units, activation = activation)
        self.hidden2 = keras.layers.Dense(units, activation = activation)
        self.main_output = keras.layers.Dense(1)
        self.aux_output = keras.layers.Dense(1)
        
    def call(self, inputs):
        input_A, input_B = inputs
        hidden1 = self.hidden1(input_B)
        hidden2 = self.hidden2(hidden1)
        concat = keras.layers.concatenate([input_A, hidden2])
        main_output = self.main_output(concat)
        aux_output = self.aux_output(hidden2)
        return main_output, aux_output

In [ ]:
model = WideAndDeepModel()