In [1]:
import numpy as np

# The Basics

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
b = np.array([[9, 8, 7], [6, 5, 4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int64')

In [10]:
a1 = np.array([1, 2, 3], dtype='int16')
print(a1)

[1 2 3]


In [11]:
a1.dtype

dtype('int16')

In [12]:
# Get Size
a.itemsize

8

In [13]:
a1.itemsize

2

In [14]:
# Get Total size
a.size * a.itemsize

24

In [15]:
a.nbytes

24

# Accessing/Changing specific elements, rows, columns

In [16]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [17]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a.shape

(2, 7)

In [19]:
# Get a specific element [r, c]
a[1, 5]

13

In [20]:
a[1, -2]

13

In [21]:
# Get s specific row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
a[:, 2]

array([ 3, 10])

In [23]:
# [start_index: end_index: stepsize]
a[0, 1: 6: 2]

array([2, 4, 6])

In [24]:
a[0, 1: -1: 2]

array([2, 4, 6])

In [25]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [26]:
a[:, 2] = [1, 2]

In [27]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [29]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Getting specific element
b[0, 1, 1]

4

In [31]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [32]:
b[:, 1, :] = [[9, 9], [8, 8]]

In [33]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of Arrays

In [34]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [38]:
np.ones((3, 3, 3), dtype='int16')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [39]:
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [40]:
# ANy other number (full-like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
# Random Decimal numbers between 0 and 1
np.random.rand(4, 2)

array([[0.38993579, 0.28983427],
       [0.01418024, 0.46287301],
       [0.50557461, 0.27980742],
       [0.75317937, 0.53726388]])

In [44]:
np.random.random_sample(a.shape)

array([[0.11684539, 0.24164387, 0.63213739, 0.21626327, 0.50572645,
        0.51265934, 0.62358026],
       [0.63874862, 0.3488062 , 0.77705515, 0.39868085, 0.71582613,
        0.72285722, 0.31321097]])

In [45]:
# Random integer Values
np.random.randint(7)

0

In [46]:
np.random.randint(7, size=(3, 3))

array([[3, 2, 2],
       [4, 3, 5],
       [1, 4, 3]])

In [47]:
np.random.randint(-4, 8, size=(3, 3))

array([[ 0, -3,  3],
       [ 5, -3,  6],
       [ 2,  4,  1]])

In [49]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [51]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [52]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
q1 = np.ones(shape=(5, 5))
print(q1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
q1[1:4, 1] = [0, 0, 0]
q1[1:4, 3] = [0, 0, 0]
print(q1)

[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
q1[1:4, 2] = [0, 9, 0]
print(q1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
# Alternate (and better) solution
q11 = np.ones(shape=(5, 5))
z = np.zeros(shape=(3, 3))
z[1, 1] = 9
q11[1:4, 1:4] = z
print(q11)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays

In [63]:
a = np.array([1, 2, 3])
b = a
print(b)

[1 2 3]


In [64]:
b[0] = 100
print(b)

[100   2   3]


In [65]:
print(a)

[100   2   3]


In [66]:
# To prevent the above use .copy
b = a.copy()
b[1] = 1
print(b)

[100   1   3]


In [67]:
print(a)

[100   2   3]


# Mathematics

In [68]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [69]:
a + 2

array([3, 4, 5, 6])

In [70]:
a - 2

array([-1,  0,  1,  2])

In [71]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [72]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [73]:
a ** 2

array([ 1,  4,  9, 16])

In [74]:
# Take the sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear algebra

In [75]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [78]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [79]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [80]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
np.min(stats)

1

In [82]:
np.min(stats, axis=0)

array([1, 2, 3])

In [83]:
np.max(stats)

6

In [84]:
np.max(stats, axis=0)

array([4, 5, 6])

In [85]:
np.max(stats, axis=1)

array([3, 6])

In [86]:
np.sum(stats)

21

In [87]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [88]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganizing Arrays

In [89]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [90]:
before.shape

(2, 4)

In [91]:
before.reshape(8, -1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [92]:
after = before.reshape((8, 1))

In [93]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [94]:
before.reshape((2, 2, -1))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [95]:
# Vertically stacking matrices
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
np.vstack([v1, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [97]:
# Horizontal Stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [98]:
# Advanced Indexing. You can index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [100]:
q2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])
q2 = q2.reshape((6, -1))
print(q2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [102]:
print(q2[2: 4, : 2])

[[11 12]
 [16 17]]


In [118]:
q2[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [130]:
q2[[0, 0, 4, 4, 5, 5], [3, 4, 3, 4, 3, 4]]

array([ 4,  5, 24, 25, 29, 30])

In [131]:
q2[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [133]:
q2[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])